version: "3"

services:
  redis:
    image: redis:4.0.5-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /tmp/data/loc-redis:/data
